### ISSUE TITLE
getRichMenuIdOfUserが404を返す

### ISSUE THREAD

**Issue by shunby** [bdm-k/potipoti#16]
```
2020-04-03T10:33:53.455214+00:00 heroku[router]: at=info method=POST path="/callback" host=potipoti.herokuapp.com request_id=94bdc221-16b1-4260-88ad-bf1d2bbdef1a fwd="147.92.150.196" dyno=web.1 connect=0ms service=11ms status=403 bytes=124 protocol=https
2020-04-03T10:33:53.715881+00:00 app[web.1]: HTTPError: Request failed with status code 404
2020-04-03T10:33:53.715892+00:00 app[web.1]: at HTTPClient.wrapError (/app/node_modules/@line/bot-sdk/dist/http.js:83:20)
2020-04-03T10:33:53.715893+00:00 app[web.1]: at /app/node_modules/@line/bot-sdk/dist/http.js:19:88
2020-04-03T10:33:53.715896+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-04-03T10:33:53.715896+00:00 app[web.1]: at async HTTPClient.get (/app/node_modules/@line/bot-sdk/dist/http.js:22:21)
2020-04-03T10:33:53.715897+00:00 app[web.1]: at async Client.getRichMenuIdOfUser (/app/node_modules/@line/bot-sdk/dist/client.js:111:21)
2020-04-03T10:33:53.715897+00:00 app[web.1]: at async shapeEvent (/app/index.js:103:27)
2020-04-03T10:33:53.715898+00:00 app[web.1]: at async handleEvent (/app/index.js:45:13)
```

**Comment by shunby** [comment]
nyan
